# project name
site_name: test

# root directoryの設定
docs_dir: "docs"

use_directory_urls: false


# theme settings
theme :
    features:
        tabs: true

    # theme名
    #name: readthedocs
    name: material


    navigation_depth: 1
    nav_style: dark

    # nextボタンの位置
    prev_next_buttons_location: both


    palette:
        # カーソルを合わせた時の色の変化
        accent: red
        # メインテーマの配色
        primary: black


# navigation pannel
nav:
    - Home: index.md

extra_css:
    - css/test.css



markdown_extensions:
    # meta data
    - meta

    # 警告文のハイライト表示
    - admonition

    # 注釈
    - footnotes

    # 定義リスト
    - def_list

    # 自動でリンクを変換
    - pymdownx.magiclink

    # markdown内のタブ機能
    - pymdownx.tabbed

    # code block nesting
    - pymdownx.superfences

    # 外部ファイルの挿入
    - pymdownx.snippets

    - pymdownx.superfences

    - pymdownx.tasklist

    # 数式を使う
    - pymdownx.arithmatex:
        generic: true

    # 目次
    - toc:
        permalink: "#"
        baselevel: 2


    # plantumlを描写できるようにする
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml




extra_javascript:
    #- javascript/extra.js
    #- javascript/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
    - search
    - table-reader

extra:
    search:
        language: 'en'
